const categories = ['英語・資格などの学習', '運動・ストレッチ・散歩', '読書・日記・瞑想'];
const reasons = ['忙しかった', '忘れていた', '疲れていた', '面倒だった', '目標が重すぎた', '意味を見失った', '完璧にやろうとした'];
let state = { screen: 'onboarding', active: 1, draftReasons: ['忙しかった', '疲れていた'], checkReasons: ['疲れていた'], habits: [
  { id: 1, name: '英語学習', category: categories[0], normalGoal: '10分だけ音読する', busyGoal: '3分だけ単語を見る', tinyGoal: '教材を開いて1文読む', purpose: '海外出張で困らないようにしたい', lastRecordOffset: 4, restarts: 2, records: ['できた', '戻るだけできた'] },
  { id: 2, name: '夜のストレッチ', category: categories[1], normalGoal: '寝る前に8分伸ばす', busyGoal: '肩だけ1分回す', tinyGoal: '深呼吸を3回する', purpose: '疲れを翌日に残しにくくしたい', lastRecordOffset: 1, restarts: 1, records: ['休む'] }
]};
const $ = (id) => document.getElementById(id);
function icon(name){ return `<span class="icon">${name}</span>`; }
function setScreen(screen){ state.screen = screen; render(); }
function totalRestarts(){ return state.habits.reduce((sum, h) => sum + h.restarts, 0); }
function activeHabit(){ return state.habits.find(h => h.id === state.active) || state.habits[0]; }
function toggle(kind, reason){ const key = kind === 'draft' ? 'draftReasons' : 'checkReasons'; state[key] = state[key].includes(reason) ? state[key].filter(r => r !== reason) : [...state[key], reason]; render(); }
function record(type, label){ state.habits = state.habits.map(h => h.id === state.active ? { ...h, restarts: type === 'tiny' && h.lastRecordOffset >= 2 ? h.restarts + 1 : h.restarts, lastRecordOffset: 0, records: [label, ...h.records].slice(0,8) } : h); render(); }
function addHabit(){ if(state.habits.length < 2){ state.habits.push({ id: Date.now(), name: $('habitName').value || '新しい習慣', category: $('category').value, normalGoal: '10分だけ進める', busyGoal: '3分だけ触れる', tinyGoal: '30秒だけ開く', purpose: $('purpose').value || '続けたい理由を忘れないため', lastRecordOffset: 0, restarts: 0, records: [] }); state.active = state.habits.at(-1).id; } setScreen('home'); }
function shell(content){ return `<main class="app-shell"><aside class="sidebar"><div class="brand"><div class="logo">三</div><div><b>三日boze</b><span>戻る力を育てる</span></div></div><nav><button class="${state.screen==='home'?'active':''}" onclick="setScreen('home')">${icon('⌂')}ホーム</button><button class="${state.screen==='restart'?'active':''}" onclick="setScreen('restart')">${icon('↻')}リスタート</button><button class="${state.screen==='report'?'active':''}" onclick="setScreen('report')">${icon('▣')}レポート</button></nav><div class="free-card"><b>無料プラン</b><p>習慣は2件まで。基本記録、リスタートチェック、標準再開プラン、月次簡易レポートを使えます。</p></div></aside><section class="content">${content}</section></main>`; }
function chips(kind, selected){ return `<div class="chips">${reasons.map(r => `<button class="${selected.includes(r)?'selected':''}" onclick="toggle('${kind}','${r}')">${r}</button>`).join('')}</div>`; }
function onboarding(){ return shell(`<div class="hero grid-2"><section><p class="eyebrow">${icon('♡')}責めないリスタート支援アプリ</p><h1>続かなかった？<br>じゃあ、戻り方を変えよう。</h1><p class="lead">三日bozeは、連続記録を競う習慣化アプリではありません。途切れた後に、何度でも戻ってくるためのアプリです。</p><div class="promise">${icon('✦')}途切れた瞬間こそ、いちばん優しく戻れる。</div></section><section class="panel form-card"><h2>過去の挫折から、最小再開ルールを作る</h2><label>続かなかった習慣<input id="habitName" value="英語学習"></label><label>カテゴリ<select id="category">${categories.map(c=>`<option>${c}</option>`).join('')}</select></label><div><span class="label">止まった理由</span>${chips('draft', state.draftReasons)}</div><label>本当の目的<textarea id="purpose" placeholder="例: 海外出張で困らないようにしたい"></textarea></label><div class="restart-plan"><b>提案:</b> 通常日は10分、忙しい日は3分、限界日は30秒だけ開く。3日空いた後は「1つだけ」で十分です。</div><button class="primary" onclick="addHabit()">無料プランで始める →</button></section></div>`); }
function home(){ const h=activeHabit(), paused=state.habits.filter(x=>x.lastRecordOffset>=2); return shell(`<header class="top"><div><p class="eyebrow">おかえりなさい</p><h1>今日は戻るだけで十分です</h1></div><button class="ghost">＋ 習慣 ${state.habits.length}/2</button></header><div class="stats"><div class="stat"><span>有効再開数</span><b>${totalRestarts()}回</b></div><div class="stat"><span>見守り中の習慣</span><b>${state.habits.length}/2</b></div><div class="stat"><span>復帰モード</span><b>${paused.length}件</b></div></div><div class="grid-2"><section class="panel"><h2>習慣を記録する</h2><div class="tabs">${state.habits.map(x=>`<button class="${x.id===h.id?'active':''}" onclick="state.active=${x.id};render()">${x.name}</button>`).join('')}</div><div class="habit-card"><p class="category">${h.category}</p><h3>${h.name}</h3><p>始めた理由: ${h.purpose}</p><div class="mini-rules"><span>通常: ${h.normalGoal}</span><span>忙しい日: ${h.busyGoal}</span><span>限界日: ${h.tinyGoal}</span></div></div><div class="record-actions"><button onclick="record('done','できた')">✓ できた</button><button onclick="record('tiny','戻るだけできた')">↻ 戻るだけできた</button><button onclick="record('rest','休む')">休む</button></div></section><section class="panel warm"><h2>復帰招待</h2>${paused.length?paused.map(x=>`<div class="notice"><b>${x.name}</b><p>${x.lastRecordOffset}日空いています。今日は30秒だけ戻りますか？</p><button onclick="state.active=${x.id};setScreen('restart')">リスタートチェックへ</button></div>`).join(''):'<p>今は大丈夫。休んだ日も、戻る準備の一部です。</p>'}</section></div>`); }
function restart(){ const h=activeHabit(), main=state.checkReasons[0]||'忙しさ'; return shell(`<div class="grid-2"><section class="panel"><p class="eyebrow">30秒で完了</p><h1>リスタートチェック</h1><p>診断ではありません。今回のつまずき傾向を一緒に軽く見て、今日の一歩を小さくします。</p>${chips('check', state.checkReasons)}<label>今の気分<select><option>少し重い</option><option>落ち着いている</option><option>かなり疲れている</option></select></label><label>今使える時間<select><option>30秒ならできる</option><option>3分ならできる</option><option>10分ならできる</option></select></label></section><section class="panel plan"><h2>標準再開プラン</h2><p>今回は「${main}」が障害だったかもしれません。</p><div class="big-action">今日の再開は、<b>${h.tinyGoal}</b> で十分です。</div><ul><li>元の目標へ一気に戻さない</li><li>始めた理由「${h.purpose}」を読み返す</li><li>次回は忙しい日のルール「${h.busyGoal}」を先に使う</li></ul><button class="primary" onclick="record('tiny','戻るだけできた')">戻るだけできた</button></section></div>`); }
function report(){ const counts={}; [...state.draftReasons,...state.checkReasons].forEach(r=>counts[r]=(counts[r]||0)+1); return shell(`<header class="top"><div><p class="eyebrow">月次簡易レポート</p><h1>戻れた事実を積み上げる</h1></div></header><div class="stats"><div class="stat"><span>有効再開数</span><b>${totalRestarts()}回</b></div><div class="stat"><span>戻るまでの平均</span><b>2.5日</b></div><div class="stat"><span>今月の記録</span><b>${state.habits.reduce((s,h)=>s+h.records.length,0)}件</b></div></div><section class="panel"><h2>よくある中断理由</h2>${Object.entries(counts).map(([r,c])=>`<div class="bar"><span>${r}</span><div><i style="width:${c*35}%"></i></div></div>`).join('')}<div class="premium"><b>プレミアムはまだ入口だけ</b><p>3回目の有効再開後に、AI再開コーチや週次レビューを提案します。無料プランではここまで使えます。</p></div></section>`); }
function render(){ $('app').innerHTML = state.screen === 'onboarding' ? onboarding() : state.screen === 'home' ? home() : state.screen === 'restart' ? restart() : report(); }
window.state=state; window.render=render; window.setScreen=setScreen; window.toggle=toggle; window.record=record; window.addHabit=addHabit; render();
